{
 "title": "Argus Dashboard (Telemetry Visualization)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(argus_container_cpu_util_pct,instance)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(argus_container_cpu_util_pct{instance=\"$instance\"},host_id)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(argus_container_cpu_util_pct{instance=\"$instance\"},container_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg by (container_id, host_id) (argus_container_cpu_util_pct{instance=~\"$instance\", host_id=~\"$host\", container_id=~\"$container\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "argus_container_cpu_util_pct{instance=~\"$instance\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Memory",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (container_id, host_id) (argus_container_memory_rss_bytes{instance=~\"$instance\"}))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network RX per container",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (container_id, host_id) (argus_container_network_rx_bytes{instance=~\"$instance\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "avg by (container_id, host_id) (argus_container_gpu_util_pct{instance=~\"$instance\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sensor temperature per container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "argus_container_sensor_temp_c{instance=~\"$instance\", host_id=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "increase(argus_pod_restarts_total{instance=~\"$instance\"}[15m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Virtual Machines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "VM CPU % (per host)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "avg by (host_id) (argus_vm_cpu_pct{instance=~\"$instance\", host_id=~\"$host\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VM CPU per zone",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "avg by (host_id, zone) (argus_vm_cpu_pct_zone{instance=~\"$instance\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VM Memory RSS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "sum by (host_id) (argus_vm_memory_rss_bytes{instance=~\"$instance\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VM CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "argus_vm_cpu_pct", "legendFormat": "__auto" }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Application CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "avg by (container_id, host_id) (argus_app_cpu_util_pct{instance=~\"$instance\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 43 },
   "targets": [
    {
     "expr": "avg by (container_id, host_id) (argus_app_error_rate_pct{instance=~\"$instance\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Request Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container_id, host_id) (argus_app_request_rate_rps{instance=~\"$instance\", host_id=~\"$host\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Orchestrator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Pod Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argus_orchestrator_pod_count{instance=~\"$instance\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Pod Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(argus_orchestrator_api_latency_ms{instance=~\"$instance\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Network Sensor Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "argus_container_sensor_temp_c{container_id=\"network_sensor\", instance=~\"$instance\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput per host (bps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "sum by (host_id) (argus_network_interface_throughput_bps{instance=~\"$instance\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "argus_network_interface_throughput_bps",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}